### ISSUE TITLE
Transfer to JuliaLang

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/VML.jl#2]
Would you mind transferring this package to JuliaLang (or perhaps we create JuliaMath)? We can add it to this team then:

https://github.com/orgs/JuliaLang/teams/julia-math-libraries/repositories

**Comment by simonster** [comment]
I'm happy to transfer this wherever.

**Comment by ViralBShah** [comment]
I have added you as an Admin to JuliaLang. You should be able to transfer there. I'll do the rest.

**Comment by simonster** [comment]
Transferred.
